-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admins
(
    id serial NOT NULL,
    organization_id integer NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" DEFAULT 'admin'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    email character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT admins_pkey PRIMARY KEY (id),
    CONSTRAINT admins_org_email_key UNIQUE (organization_id, email),
    CONSTRAINT admins_organization_id_email_key UNIQUE (organization_id, email)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id serial NOT NULL,
    organization_id integer,
    action character varying(100) COLLATE pg_catalog."default" NOT NULL,
    actor_id integer NOT NULL,
    actor_role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    details jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.candidates
(
    id serial NOT NULL,
    organization_id integer NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    bio text COLLATE pg_catalog."default",
    photo_url text COLLATE pg_catalog."default",
    yes_or_no text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT candidates_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.election_settings
(
    id serial NOT NULL,
    organization_id integer NOT NULL,
    is_active boolean DEFAULT false,
    title character varying(255) COLLATE pg_catalog."default",
    academic_year character varying(50) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    logo_url text COLLATE pg_catalog."default",
    updated_by integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT election_settings_pkey PRIMARY KEY (id),
    CONSTRAINT election_settings_organization_id_key UNIQUE (organization_id)
);

CREATE TABLE IF NOT EXISTS public.organizations
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    phone character varying(50) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    created_by integer,
    deleted_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT organizations_pkey PRIMARY KEY (id),
    CONSTRAINT organizations_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.owners
(
    id serial NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT owners_pkey PRIMARY KEY (id),
    CONSTRAINT owners_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.tokens
(
    id serial NOT NULL,
    organization_id integer NOT NULL,
    voter_id integer,
    token_value character varying(20) COLLATE pg_catalog."default" NOT NULL,
    used boolean DEFAULT false,
    expires_at timestamp without time zone NOT NULL,
    generated_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tokens_pkey PRIMARY KEY (id),
    CONSTRAINT tokens_token_value_key UNIQUE (token_value)
);

CREATE TABLE IF NOT EXISTS public.voters
(
    id serial NOT NULL,
    organization_id integer NOT NULL,
    student_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    department character varying(100) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    has_voted boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT voters_pkey PRIMARY KEY (id),
    CONSTRAINT voters_organization_id_student_id_key UNIQUE (organization_id, student_id)
);

CREATE TABLE IF NOT EXISTS public.votes
(
    id serial NOT NULL,
    organization_id integer NOT NULL,
    voter_id integer,
    candidate_id integer,
    voted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ip_address inet,
    student_id character varying(50) COLLATE pg_catalog."default",
    full_name character varying(255) COLLATE pg_catalog."default",
    candidate_name character varying(255) COLLATE pg_catalog."default",
    candidate_position character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT votes_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.admins
    ADD CONSTRAINT admins_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_audit_logs_org
    ON public.audit_logs(organization_id);


ALTER TABLE IF EXISTS public.candidates
    ADD CONSTRAINT candidates_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_candidates_org
    ON public.candidates(organization_id);


ALTER TABLE IF EXISTS public.election_settings
    ADD CONSTRAINT election_settings_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS election_settings_organization_id_key
    ON public.election_settings(organization_id);


ALTER TABLE IF EXISTS public.election_settings
    ADD CONSTRAINT election_settings_updated_by_fkey FOREIGN KEY (updated_by)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.organizations
    ADD CONSTRAINT organizations_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.owners (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tokens
    ADD CONSTRAINT tokens_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tokens
    ADD CONSTRAINT tokens_voter_id_fkey FOREIGN KEY (voter_id)
    REFERENCES public.voters (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.voters
    ADD CONSTRAINT voters_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.votes
    ADD CONSTRAINT votes_candidate_id_fkey FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.votes
    ADD CONSTRAINT votes_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_votes_org
    ON public.votes(organization_id);


ALTER TABLE IF EXISTS public.votes
    ADD CONSTRAINT votes_voter_id_fkey FOREIGN KEY (voter_id)
    REFERENCES public.voters (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;